### PR TITLE
Make value of $uri_string a property of $router

### PR DESCRIPTION
**Pull request by jmtaylor**
This is useful when falling through, and need to alter the url in order to hit a different route.

### CODE REVIEW

**Comment by rsanchez** [comment]
This looks great. A few requests:

Add a *protected* property $uriString (w/ docblock) to the Router class.

Now, I assume you are doing this in your code somewhere:

```
$router->uriString = 'foo/bar';
```

But since that property will now be protected, you won't be able to do that anymore.

So, I'd also like to see a `setUriString($uriString)` method on the Router class. And a `getUriString()` method if you think that's necessary.

Thanks for the contribution!

**Comment by jmtaylor** [comment]
I made ```$uriString``` a protected property, and added ```setUri()``` and ```getUri()``` methods for interacting with it. Would you like me to update it to a minor SemVer update now that it's going to be an official new feature?

**Comment by rsanchez** [comment]
This looks great, thanks. I agree that a bump to 1.1.0 is warranted here.

**Comment by jmtaylor** [comment]
Ok, version updated to 1.1.0.

**Pull request merged**
